### PR TITLE
Feature: added navigate page in mobile app

### PR DESCRIPTION
**Pull request by 0xSwapFeeder**
# Description

Added a Navigate page that allows to filter both plugs and services and plugs by their innate data.

# Changes include

- [ ] Chore (change that needs to be done without effects on features)
- [ ] Bugfix (change that solves an issue)
- [x] New feature (change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Changes Type

- [ ] backend update
- [x] mobile update
- [ ] web update

# Checklist

- [x] I have assigned this PR to the reviewer
- [x] I have added at least 1 reviewer
- [ ] I have updated the documentation
- [ ] I have updated the README.md
- [x] I have manually tested the code
- [ ] I have added/updated tests

### CODE REVIEW

**Review by 0xMemoryGrinder — COMMENTED** [review]
Code review done, will perform functional test soon

**Comment by 0xMemoryGrinder** [comment]
Functional review is done, but you could make the search interactive by displaying only matched search when input in searchbar change, not by clicking enter

**Comment by 0xSwapFeeder** [comment]
Was already instant on change filter on my side maybe you tried to search like 'twit' which validates also plugs who have the service twitter as action or trigger for instance. Do you want me to add some kind of check boxes to show only plugs or services ?

**Comment by 0xMemoryGrinder** [comment]
My bad, will do later ofr the checkboxes but good idea

**Review by 0xMemoryGrinder — APPROVED** [review]

**Pull request merged**
